// Inhalte des Kurses — 8 Module, 36 Lektionen.
//
// Gleiche Trennung wie bei roadmap-data.js: hier stehen die Texte, in
// views/admin-kurs.js nur die Darstellung. Wer den Kurs fortschreibt, fasst
// nur diese Datei an.
//
// Aufbau eines Moduls: { id, name, wann, from, to, ziel, lessons }
//   from/to  — bestimmen, welches Modul „das aktuelle" ist (aus dem Datum).
//   ziel     — was am Ende des Moduls koennen soll.
//
// Aufbau einer Lektion: [id, titel, lernen, check, [suchbegriffe]]
//   id       — stabiler Schluessel, landet als Haken in roadmap/valentin.kurs.
//              NIE nachtraeglich aendern, sonst verwaist der gesetzte Haken.
//   lernen   — der Lerninhalt.
//   check    — „verstanden, wenn ..." — der Haken gehoert an DIESEN Punkt,
//              nicht ans Video-gesehen-haben.
//   suchbegriffe — werden in der View zu YouTube-Suchlinks; bewusst KEINE
//              Video-IDs, die sind in einem Jahr tot.

// --- Module ---------------------------------------------------------
export const MODS=[
{id:'m1',name:'Sales & Preise',wann:'Sept – Okt 2026',from:'2026-09-01',to:'2026-10-31',
 ziel:'Du kannst einen Preis nennen, ohne dich zu entschuldigen, und die Deussen-Verhandlung im November mit einem Plan führen.',
 lessons:[
  ['m1-1','Die drei Preismodelle',
   'Stunde, Projekt, Wert — wann welches Modell passt und warum Stundenpreise dich deckeln. Verstehe, was „Price the client, not the job" bedeutet: der gleiche Film ist für ein Autohaus 800 € wert und für eine Händlergruppe 8.000 €.',
   'Du kannst für Deussen, Röstzeit und ein fiktives Autohaus jeweils sagen, welches Modell du nutzt und warum — in je einem Satz.',
   ['Chris Do value based pricing','The Futur price the client not the job','hourly vs project vs value pricing creative']],
  ['m1-2','Der Discovery-Call',
   'Welche Fragen du stellst, bevor du einen Preis nennst: Ziel, Erfolgsmessung, was passiert, wenn es nicht klappt, Budgetrahmen. Lerne die Reihenfolge — erst Wert verstehen, dann Preis.',
   'Du hast ein Skript mit 8 Fragen geschrieben und es einmal mit einem Freund als Rollenspiel durchgespielt, ohne auf den Zettel zu schauen.',
   ['The Futur discovery call questions','sales call script creative freelancer','how to ask about budget client call']],
  ['m1-3','Einwände und Verhandlung',
   'Die vier Standard-Einwände („zu teuer", „ich überleg es mir", „andere machen das billiger", „wir machen das intern") und was du jeweils sagst. Lerne, Schweigen auszuhalten und nicht als Erster nachzugeben.',
   'Du kannst zu jedem der vier Einwände deine Antwort auswendig sagen — und du hast die Deussen-Verhandlung einmal komplett als Rollenspiel durchgespielt, inklusive des Moments, in dem sie „nein" sagen.',
   ['Chris Do handling objections too expensive','negotiation for creatives never split the difference','how to respond client says too expensive']],
  ['m1-4','Retainer bauen und pitchen',
   'Aufbau eines Retainer-Angebots: Umfang, Drehtag, Turnaround, Korrekturschleifen, Laufzeit, Kündigung, was passiert bei Mehrbedarf. Und wie du ihn gegen Einzelaufträge argumentierst.',
   'Du hast ein Retainer-Angebot als einseitiges PDF für ein fiktives Autohaus geschrieben, das ein Fremder versteht, ohne dich zu fragen.',
   ['videographer retainer package how to structure','how to pitch retainer deal videographer','monthly content retainer agreement template']],
  ['m1-5','Der Reichweiten-Report als Verkaufswerkzeug',
   'Wie du Instagram- und TikTok-Insights liest (Reichweite, Reach vs. Impressions, Watch Time, Follower-Quelle) und daraus eine Seite machst, die ein Kunde versteht. Was du weglässt, ist wichtiger als was du reinnimmst.',
   'Dein Deussen-Report ist fertig, eine Seite, und Nicolai versteht in 30 Sekunden, was sich seit dir verändert hat.',
   ['instagram insights explained reach impressions','how to present social media results to client','social media report one page template']],
 ]},
{id:'m2',name:'Automotive Handwerk',wann:'Nov – Dez 2026',from:'2026-11-01',to:'2026-12-31',
 ziel:'Deine Auto-Aufnahmen sehen nicht mehr nach Handy aus. Du weißt vor dem Dreh, welche 12 Einstellungen du brauchst.',
 lessons:[
  ['m2-1','Licht auf Lack',
   'Warum Autos schwer zu filmen sind: Lack ist ein Spiegel. Lerne Reflexionsmanagement — Position zur Lichtquelle, CPL richtig eindrehen, große weiche Flächen (Himmel, Hallendecke) als Reflektor nutzen, Sonnenstand planen.',
   'Du kannst bei einem Auto in der Remise erklären, wo du den Kameraplatz wählst und warum — bevor du die Kamera hochhebst. Und du hast eine Aufnahme mit und ohne CPL nebeneinander gelegt und siehst den Unterschied.',
   ['how to light a car for video reflections','circular polarizer car videography','car photography lighting reflections explained']],
  ['m2-2','Die 12 Einstellungen',
   'Die Grundgrammatik eines Auto-Films: Establishing, Front-Hero, Profil, Heck, drei Details (Badge, Rad, Licht), Interieur, Türöffnung, Bewegung (Fahrt), Bewegung (Kamera um das Auto), Menschen-Moment. Lerne, welche Brennweite und welche Höhe jede braucht.',
   'Du hast eine Shotlist mit 12 Einstellungen geschrieben, sie an einem Auto abgedreht, und beim Sichten fehlt nichts, was du für einen 60-Sekünder brauchst.',
   ['car commercial shot list','automotive cinematography shots breakdown','how to film a car cinematic b-roll']],
  ['m2-3','Gimbal-Bewegung mit Absicht',
   'Nicht „Gimbal bewegen", sondern: Orbit, Push-in, Reveal, Parallax, Low-Tracking. Jede Bewegung hat einen Grund — sie enthüllt, sie folgt, sie betont. Lerne, langsam zu sein.',
   'Du kannst 5 Gimbal-Bewegungen benennen, hast jede an einem Auto gedreht, und kannst bei jeder sagen, was sie erzählt.',
   ['DJI RS4 Mini cinematic movements','gimbal moves for car videos','parallax reveal gimbal technique']],
  ['m2-4','Rolling Shots',
   'Auto aus einem fahrenden Auto filmen: Verschlusszeit 1/20–1/40 für Radunschärfe, Geschwindigkeit, Abstand, Sicherheit, Absprache mit dem Fahrer. Was man ohne Rig sauber hinbekommt und was nicht.',
   'Du hast einen Rolling Shot gedreht, bei dem die Räder verwischen, das Auto aber scharf ist.',
   ['how to shoot rolling shots car','rolling shot shutter speed car video','car to car tracking shot tutorial']],
  ['m2-5','Grading und Sound für Autos',
   'Auto-Grading: Lack sättigen ohne Haut zu ruinieren, Spiegelungen kontrollieren, Kontrast in Chrom. Sound: Motor, Reifen, Tür, Blinker — Foley und Library, und warum ein Auto-Film ohne Sounddesign tot ist.',
   'Dein erstes Hero-Piece hat ein Grading, das das Auto teurer aussehen lässt als in Wirklichkeit, und einen Sound-Mix, bei dem jede Bewegung im Bild ein Geräusch hat.',
   ['car commercial color grading davinci resolve','automotive sound design tutorial','how to add car sounds to video editing']],
 ]},
{id:'m3',name:'Content-Strategie',wann:'Jan – Feb 2027',from:'2027-01-01',to:'2027-02-28',
 ziel:'Du kannst einem Kunden erklären, warum sein Content nicht funktioniert und was du ändern würdest — mit Daten, nicht mit Gefühl.',
 lessons:[
  ['m3-1','Wie Empfehlungsalgorithmen entscheiden',
   'Was TikTok, Reels und Shorts wirklich messen: Watch Time, Completion, Rewatches, Shares, Swipe-Away in Sekunde 1–3. Warum Follower fast egal sind und warum der Hook nicht nur hält, sondern auch bestimmt, wem das Video gezeigt wird.',
   'Du kannst einem Kunden in zwei Minuten erklären, warum sein 10.000-Follower-Account 300 Views macht — ohne das Wort „Algorithmus" zu benutzen.',
   ['how the tiktok algorithm works 2026','Paddy Galloway retention','instagram reels algorithm explained watch time']],
  ['m3-2','Hooks und Packaging',
   'Die ersten 1–3 Sekunden: visuell, textlich, auditiv. Die 6 Hook-Typen (Frage, Widerspruch, Ergebnis zuerst, Bewegung, Zahl, Du-Ansprache). Warum kleine Creator 95 % ihrer Zeit ins Filmen stecken und der Hebel im Packaging liegt.',
   'Du hast für ein Auto-Video 20 Hooks geschrieben, die 3 besten getestet, und kannst sagen, welcher Typ bei dir funktioniert.',
   ['viral hooks short form video','Colin and Samir hooks first 3 seconds','how to write hooks for reels']],
  ['m3-3','Retention lesen',
   'Retention-Kurven in Insights finden und lesen: der Einbruch bei Sekunde 2, der Abfall in der Mitte, der Spike beim Twist. Jede Delle ist eine Stelle, an der das Video kaputt ist.',
   'Du hast die Retention-Kurven deiner letzten 10 Posts nebeneinander gelegt und kannst bei jedem sagen, wo und warum Leute gehen.',
   ['how to read audience retention graph','retention analysis short form content','tiktok analytics average watch time explained']],
  ['m3-4','Formate statt Einzelvideos',
   'Warum wiederholbare Formate schlagen, was ständig neu ist: Wiedererkennung, Produktionsgeschwindigkeit, Erwartung. Dein 3-Part-Auto-Format ist ein Format. Lerne, eins zu designen: Hook-Struktur, Länge, Rhythmus, Ende.',
   'Du hast für einen Kunden ein Format definiert (Name, Struktur, Länge, Beispiel) und drei Folgen davon geplant.',
   ['repeatable content formats social media','content series strategy creators','Colin and Samir format development']],
  ['m3-5','Die Kundenanalyse',
   'Die Methode, mit der du jeden Kunden-Account in einer Stunde auswertest: letzte 20 Posts, Top 3 / Flop 3, Muster erkennen, eine Empfehlung. Das ist dein Verkaufsdokument und dein Retainer-Argument.',
   'Du hast die Deussen-Analyse gemacht und daraus eine Format-Empfehlung geschrieben, die auf einer Seite passt und mit „ich würde…" beginnt.',
   ['social media audit how to','content audit template instagram','analyze competitor social media content']],
 ]},
{id:'m4',name:'Regie & Bildgestaltung',wann:'Mär – Apr 2027',from:'2027-03-01',to:'2027-04-30',
 ziel:'Dein Spec-Spot in den Osterferien hat eine Idee, nicht nur schöne Bilder. Du entscheidest am Set, statt zu sammeln.',
 lessons:[
  ['m4-1','Von der Idee zum Konzept',
   'Ein Werbefilm hat eine Idee, die in einem Satz passt. Lerne die Struktur: Insight → Idee → Bild. Studiere, wie 30-Sekünder von großen Marken eine einzige Sache sagen — und alles andere weglassen.',
   'Du hast für deinen Spec-Spot die Idee in einem Satz aufgeschrieben, und drei Leute, die ihn lesen, beschreiben denselben Film.',
   ['how to develop a commercial concept','advertising big idea explained','StudioBinder commercial breakdown']],
  ['m4-2','Bildkomposition und Blocking',
   'Wo steht was im Bild und warum: Drittel, Führungslinien, Tiefe, negative Fläche, Symmetrie als Statement. Blocking: wo steht das Auto, wo die Person, wo die Kamera — und wie sich das mit der Zeit verändert.',
   'Du kannst bei 5 Frames aus Auto-Werbespots erklären, warum die Komposition so ist — und hast dein Spec-Konzept als 10 Skizzen gezeichnet.',
   ['cinematic composition rules explained','blocking and staging for directors','StudioBinder composition']],
  ['m4-3','Licht als Erzählung',
   'Hartes vs. weiches Licht, Motivated Light, Kontrastverhältnisse, Farbtemperatur als Stimmung. Für Autos: Nacht mit einer Lichtquelle, Golden Hour, Halle mit Toplight. Wann du mit einem Licht mehr erreichst als mit drei.',
   'Du hast dieselbe Einstellung dreimal beleuchtet (hart, weich, Gegenlicht) und kannst sagen, welche Stimmung jede erzeugt.',
   ['cinematic lighting techniques one light','motivated lighting explained','how to light a car at night video']],
  ['m4-4','Schnitt-Denken beim Drehen',
   'Was du drehen musst, damit es sich schneiden lässt: Coverage, Übergänge, Rhythmus, Anschlüsse, Reaktionen. Warum ein Regisseur, der Schnitt versteht, weniger dreht und mehr bekommt.',
   'Beim Spec-Spot hast du jede Einstellung mit dem Gedanken gedreht, was davor und danach kommt — und beim Schneiden fehlt keine Brücke.',
   ['shooting for the edit','directing coverage explained','editing in camera technique']],
  ['m4-5','Regie am Set',
   'Wie du einen Drehtag führst: Ablaufplan, Prioritäten, Entscheidungen unter Zeitdruck, mit Menschen vor der Kamera reden, wann du „weiter" sagst. Was am Set nur du entscheiden kannst.',
   'Der Spec-Spot ist an drei Tagen gedreht, du hast den Plan eingehalten, und du hast mindestens einmal bewusst eine Einstellung gestrichen, um eine bessere zu bekommen.',
   ['how to direct a commercial shoot','directing tips first time director','call sheet and shot list for shoot day']],
 ]},
{id:'m5',name:'Creative Direction & Treatment',wann:'Mai – Jun 2027',from:'2027-05-01',to:'2027-06-30',
 ziel:'Du hast eine Handschrift und kannst sie in einem Treatment beschreiben, das ein Kunde versteht und kauft.',
 lessons:[
  ['m5-1','Werbefilme lesen',
   'Die Methode, mit der du jeden Spot in 10 Minuten auseinandernimmst: Idee, Struktur, Bildsprache, Rhythmus, Sound, was er auslässt. Baue eine Referenzbibliothek — 30 Spots, jeder mit drei Sätzen.',
   'Du hast 30 Auto- und Premium-Spots analysiert und kannst bei jedem in einem Satz sagen, was ihn funktionieren lässt.',
   ['best car commercials of all time analysis','commercial director breakdown ad','Porsche commercial cinematography']],
  ['m5-2','Deine Handschrift',
   'Was deine Bildsprache ausmacht — nicht was du magst, sondern was du wiederholst. Farbe, Tempo, Licht, Perspektive, Sound. Lerne, sie zu benennen, damit ein DoP sie umsetzen kann, ohne dass du hinter ihm stehst.',
   'Du hast deine Handschrift in fünf Sätzen beschrieben und ein Moodboard mit 15 Bildern gebaut, die alle zu diesen Sätzen passen — und eins, das nicht passt, um den Unterschied zu zeigen.',
   ['find your visual style as a filmmaker','director signature style analysis','how to build a mood board for film']],
  ['m5-3','Das Treatment',
   'Das Dokument, mit dem Werbefilme gewonnen werden: Idee, Ton, Bildsprache, Struktur, Referenzen, warum das für die Marke funktioniert. 6–12 Seiten, mehr Bild als Text. Lerne die Struktur und den Ton.',
   'Du hast ein Treatment für einen fiktiven Auftrag (Autohaus-Imagefilm) geschrieben, das jemand versteht, der dich nicht kennt — und das du ohne Scham einem echten Kunden zeigen würdest.',
   ['how to write a director treatment','commercial director treatment example','treatment template for commercials']],
  ['m5-4','Marke verstehen',
   'Was ein Kunde meint, wenn er „Premium" sagt. Markenwerte, Zielgruppe, Positionierung — und wie sich das in Bild übersetzt. Warum Porsche anders aussieht als Mercedes, obwohl beide „Luxus" sagen.',
   'Du kannst bei drei Automarken sagen, was sie visuell unterscheidet und warum — und für eine davon einen Spot skizzieren, der zur Marke passt.',
   ['brand strategy for creatives explained','The Futur brand positioning','automotive brand identity comparison']],
  ['m5-5','Referenzen und Geschmack',
   'Geschmack ist trainierbar: viel gutes Zeug sehen, bewusst. Filme, Fotografie, Architektur, Mode — nicht nur Werbung. Baue eine Routine: eine Referenz pro Tag, drei Sätze.',
   'Du hast 30 Tage lang täglich eine Referenz notiert und kannst am Ende sagen, was sich an deinem Blick verändert hat.',
   ['taste and reference for filmmakers','cinematography references directors study','how to develop taste as a creative']],
 ]},
{id:'m6',name:'KI, SEO & GEO',wann:'Jul – Aug 2027',from:'2027-07-01',to:'2027-08-31',
 ziel:'KI beschleunigt deine Arbeit an fünf Stellen, und vale-video.de ist die Antwort, wenn jemand eine KI nach Automotive-Videografen fragt.',
 lessons:[
  ['m6-1','KI in deinem Workflow',
   'Wo KI dir Zeit spart und wo nicht: Recherche, Hook-Varianten, Captions, Analyse, Angebote — ja. Bildmaterial im Kundenprojekt ohne Kennzeichnung — nein. Baue für jeden Ja-Fall einen festen Prompt oder Skill.',
   'Du hast für die fünf Fälle je einen wiederverwendbaren Prompt oder Skill und nutzt sie seit zwei Wochen ohne nachzudenken.',
   ['AI workflow for content creators','Claude for marketing workflow','AI tools for video production business']],
  ['m6-2','Der automatische Kundenreport',
   'Analytics-Export → Claude → Monatsreport. Baue den Workflow so, dass er in 15 Minuten läuft, nicht in zwei Stunden. Das ist gleichzeitig ein verkaufbares Retainer-Feature.',
   'Der Report für einen Kunden entsteht aus dem Export in unter 15 Minuten und sieht jeden Monat gleich aus.',
   ['automate social media report with AI','instagram insights export analyze','Claude data analysis report generation']],
  ['m6-3','Wie KI-Suche funktioniert',
   'Warum ChatGPT, Claude und Perplexity anders auswählen als Google: Entities, Zitierbarkeit, Antwortformate, strukturierte Daten. GEO und AEO als Begriffe verstehen, ohne den Hype.',
   'Du kannst in drei Sätzen erklären, warum eine Seite von einer KI zitiert wird und eine andere nicht.',
   ['generative engine optimization explained','AEO GEO vs SEO 2026','how AI search chooses sources']],
  ['m6-4','vale-video.de für KI-Suche',
   'Schema-Markup (LocalBusiness, VideoObject), klare Entity-Signale, Antwortformate, FAQ-Struktur. Umsetzen, dann testen: drei KIs nach „Automotive Videograf Düsseldorf" fragen.',
   'Mindestens eine KI nennt vale-video.de bei der Frage — und du weißt, welche Änderung das ausgelöst hat.',
   ['schema markup local business tutorial','optimize website for ChatGPT search','JSON-LD VideoObject schema']],
 ]},
{id:'m7',name:'Pitchen & Präsentieren',wann:'Sep – Okt 2027',from:'2027-09-01',to:'2027-10-31',
 ziel:'Du kannst vor fünf Leuten mit Budget stehen und einen Auftrag über 2.500 € gewinnen.',
 lessons:[
  ['m7-1','Das Pitch-Deck',
   'Struktur eines Decks, das gewinnt: Problem des Kunden, Idee, Beweis (Cases, Zahlen), Ablauf, Preis, nächster Schritt. 10 Seiten, nicht 30. Was rausfliegt, ist wichtiger als was drin ist.',
   'Du hast ein Deck für einen echten Prospect gebaut, das ein Fremder in fünf Minuten versteht — und du hast es einmal laut präsentiert und gestoppt.',
   ['pitch deck for creative agency','how to pitch a video project to a client','The Futur how to present to clients']],
  ['m7-2','Präsentieren',
   'Sprechen vor Leuten mit Geld: Tempo, Pausen, Blickkontakt, Fragen aushalten, nicht rechtfertigen. Du bist 18, sie sind 45 — was das für deine Haltung heißt und was nicht.',
   'Du hast einen Pitch vor zwei Leuten gehalten, die dich kritisch befragt haben, ohne ins Rechtfertigen zu kippen.',
   ['how to present creative work to clients','Chris Do presenting to clients','public speaking for introverts business']],
  ['m7-3','Der Follow-up-Prozess',
   'Was nach dem Pitch passiert: Timing, Ton, wann du nachhakst, wann du loslässt. Warum die meisten Aufträge im Follow-up gewonnen werden, nicht im Pitch.',
   'Du hast einen Follow-up-Ablauf (Tag 1, 3, 7, 14) mit Vorlagen, und nutzt ihn bei jedem offenen Angebot.',
   ['follow up after proposal without being annoying','client follow up email sequence freelancer','closing deals follow up strategy']],
  ['m7-4','Große Kunden verstehen',
   'Wie Autohausgruppen, Marketingabteilungen und Agenturen einkaufen: wer entscheidet, wer bezahlt, wer dich empfiehlt. Warum du oft als Zulieferer einer Produktionsfirma reinkommst, bevor die Marke dich direkt bucht.',
   'Du kannst für einen konkreten großen Kunden aufzeichnen, wer dort entscheidet und über wen du reinkommst.',
   ['how to get commercial clients as a filmmaker','production company subcontracting director','how big brands hire video production']],
 ]},
{id:'m8',name:'Delegieren & Agentur-Basics',wann:'Nov – Dez 2027',from:'2027-11-01',to:'2027-12-31',
 ziel:'Dein erster Editor liefert in deiner Qualität, ohne dass du daneben sitzt.',
 lessons:[
  ['m8-1','Prozesse aufschreiben',
   'Deinen Schnitt- und Grading-Prozess so dokumentieren, dass ihn ein Fremder ausführt: Ordnerstruktur, Namenskonvention, Node-Tree, Export-Settings, Übergabe. Wenn du es nicht aufschreiben kannst, kannst du es nicht abgeben.',
   'Ein Editor hat mit deiner Doku ein Video geschnitten, ohne dir eine Frage zu stellen — und das Ergebnis war zu 80 % dein Stil.',
   ['how to create SOPs for video editing','documenting workflow for freelancers','editing style guide for team']],
  ['m8-2','Briefen und Feedback geben',
   'Wie du einem Freelancer sagst, was du willst, bevor er anfängt — und wie du Feedback gibst, das er umsetzen kann („der Cut bei 0:14 ist zu früh" statt „irgendwie nicht mein Vibe").',
   'Du hast drei Feedbackrunden mit deinem Editor durch, und die dritte Version brauchte nur noch eine Anmerkung.',
   ['how to give feedback to video editor','creative brief for freelancers','directing editors remote feedback']],
  ['m8-3','Kalkulation mit Fremdkosten',
   'Wenn ein Editor 120 € kostet, wie viel muss das Video kosten? Marge, Puffer, was du an den Kunden weitergibst. Die einfachste Formel, die du bei jedem Angebot anwendest.',
   'Du hast für deine drei Retainer ausgerechnet, was nach Fremdkosten bleibt — und den Preis angepasst, wo die Marge unter 60 % lag.',
   ['pricing with subcontractors margin','agency pricing markup on freelancers','how to calculate profit margin creative services']],
 ]},
];

// --- Feste Texte ----------------------------------------------------
// Der Nordstern: wofuer der ganze Kurs da ist. Unveraendert aus der Vorlage.
export const NORDSTERN =
  'Du wirst der, den eine Marke anruft, weil sie deine Bildsprache will — und der ein Team führt, das sie umsetzt. Regie und Bildgestaltung sind dein Handwerk. Editing, Sound und Grading lernst du bis „ich sehe sofort, was falsch ist". Strategie und Pitchen sind das, womit du den Auftrag gewinnst.';
export const LISTEN_HINWEIS = 'Auf eine Lektion tippen für Lerninhalt, Verstanden-Check und Suchbegriffe. Haken links, wenn der Check bestanden ist — nicht wenn du das Video gesehen hast.';
